server :
  port : 8086
application:
  name: gliiterbox

spring :
  datasource :
    url : jdbc:h2:mem:testdb
    driverClassName : org.h2.Driver
    username : sa
    password :
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
    settings:
     web-allow-others: true  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
demo: prateek
